server:
  port: 8084

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: traceability

appDescription: "Pragma Powerup"
appVersion: "1.0.0"

jwt:
  secret: "qasshtipuuwnmcbwjcalibcieebnjolño29jne9djsallsdj-sdoo-ksks-o"
